const Discord = require("discord.js");
module.exports = {
  name: "cat",
  category: "Fun",
  description: "Get ~~pussy~~ kitty pics",
  cooldown: 20,
  aliases: ["kitty"],
  execute(bot, message, args) {
    const list = [
      "https://noodle.hep.gg/1ln3xfYFG",
      "https://noodle.hep.gg/KHSqXIqXK",
      "https://noodle.hep.gg/pC2waKlFR",
      "https://noodle.hep.gg/Q19teYc6F",
      "https://noodle.hep.gg/WBrWRXHuu",
      "https://noodle.hep.gg/Qu6C5Man1",
      "https://noodle.hep.gg/Qh4j0FjfY",
      "https://noodle.hep.gg/TDNR4OrNX",
      "https://noodle.hep.gg/95Z_Lo1Wl",
      "https://noodle.hep.gg/7rHfIOStz",
      "https://noodle.hep.gg/C9ini0OA6",
      "https://noodle.hep.gg/RxIxKsTVG",
      "https://noodle.hep.gg/rpC53jVJq",
      "https://noodle.hep.gg/yypycA7M5",
      "https://noodle.hep.gg/607n08pCD",
      "https://noodle.hep.gg/wCdxdIk3T",
      "https://noodle.hep.gg/9tyl9TB0J",
      "https://noodle.hep.gg/XHcuuqGI5",
      "https://noodle.hep.gg/-j3zVASz5",
      "https://noodle.hep.gg/jJFJSvgtK",
      "https://noodle.hep.gg/8IWv4j4lO",
      "https://noodle.hep.gg/jNyN5qRvQ",
      "https://noodle.hep.gg/2WngNXxZz",
      "https://noodle.hep.gg/1mlyO7SD9",
      "https://noodle.hep.gg/JGL8N2Izj",
      "https://noodle.hep.gg/FGG1KJDyd",
      "https://noodle.hep.gg/6MFULdlwG",
      "https://noodle.hep.gg/T1MtblXRJ",
      "https://noodle.hep.gg/bW5VmRKTI",
      "https://noodle.hep.gg/NxJdk1FTI",
      "https://noodle.hep.gg/h40-Civ7u",
      "https://noodle.hep.gg/i3-dyxIMK",
      "https://noodle.hep.gg/B7ewZKTcg",
      "https://noodle.hep.gg/v2R8E-s0y",
      "https://noodle.hep.gg/kwgl1F2yu",
      "https://noodle.hep.gg/76SPS02Ep",
      "https://noodle.hep.gg/39mdNNb1i",
      "https://noodle.hep.gg/Wv0ZNr0CW",
      "https://noodle.hep.gg/Pdaph19G6",
      "https://noodle.hep.gg/vZQ5MtpFV",
      "https://noodle.hep.gg/noqFLKGaQ",
      "https://noodle.hep.gg/lLskHM8_o",
      "https://noodle.hep.gg/aHfWGbnxK",
      "https://noodle.hep.gg/JfOOo0xBe",
      "https://noodle.hep.gg/hdn4PFlTM",
      "https://noodle.hep.gg/tTTI86r8f",
      "https://noodle.hep.gg/h9ATO-zlb",
      "https://noodle.hep.gg/f6fUs3B7m",
      "https://noodle.hep.gg/VsuBoAS9g",
      "https://noodle.hep.gg/-chkjiPrg",
      "https://noodle.hep.gg/BMZedVSnV",
      "https://noodle.hep.gg/RgswPExA1",
      "https://noodle.hep.gg/Q5y3j8UzK",
      "https://noodle.hep.gg/x1QFdYfO8",
      "https://noodle.hep.gg/Ez2LbiGuR",
      "https://noodle.hep.gg/NqRl9it__",
      "https://noodle.hep.gg/fschqii1O",
      "https://noodle.hep.gg/JCE69pvKJ",
      "https://noodle.hep.gg/-cvncFTdV",
      "https://noodle.hep.gg/4MLoqPcaX",
      "https://noodle.hep.gg/fESA-W9Og",
      "https://noodle.hep.gg/1KzEstzij",
      "https://noodle.hep.gg/a7aR7HznS",
      "https://noodle.hep.gg/a3ENAdm3Y",
      "https://noodle.hep.gg/mw_Toj4Oq",
      "https://noodle.hep.gg/omoyYD45H",
      "https://noodle.hep.gg/4WaRuBlS2",
      "https://noodle.hep.gg/YC1ZISnQI",
      "https://noodle.hep.gg/A4jzy-BzQ",
      "https://noodle.hep.gg/U_zV8H2bi",
      "https://noodle.hep.gg/o4wvJrFW1",
      "https://noodle.hep.gg/cQf5iHEIc",
      "https://noodle.hep.gg/YSmzDPgmS",
      "https://noodle.hep.gg/z4xdlk8Yf",
      "https://noodle.hep.gg/wo-cOrZ9I",
      "https://noodle.hep.gg/5DE2k-evw",
      "https://noodle.hep.gg/ik1eZp3Li",
      "https://noodle.hep.gg/UmSyU_kY9",
      "https://noodle.hep.gg/5t2xd6Qk2",
      "https://noodle.hep.gg/qZFNyOMwj",
      "https://noodle.hep.gg/oOAoFMQgA",
      "https://noodle.hep.gg/1iubxVrUG",
      "https://noodle.hep.gg/b2_X5GvGI",
      "https://noodle.hep.gg/VJNEcF6eW",
      "https://noodle.hep.gg/kPq8qrRKU",
      "https://noodle.hep.gg/WQSz9CGH7",
      "https://noodle.hep.gg/xVoNSjX_M",
      "https://noodle.hep.gg/lpkg3BZFA",
      "https://noodle.hep.gg/Lt0dgEsxK",
      "https://noodle.hep.gg/wtQccZfue",
      "https://noodle.hep.gg/sv3DbIBpO",
      "https://noodle.hep.gg/VvMM1UcoL",
      "https://noodle.hep.gg/1BKzEq69w"
      ]
    const pussyEmbed = new Discord.MessageEmbed()
    .setAuthor(message.author.tag, message.author.displayAvatarURL(),'https://discord.gg/Se6tgufK25')
    .setColor('BLUE')
    .setImage(list[Math.floor(Math.random() * list.length)])
    .setTimestamp()
    .setFooter('Here is some puss')
      message.channel.send(pussyEmbed)
 }
}
